language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
sudo: required
dist: trusty
install:
  - pip install -e .[test]
script:
  - flake8 -v setup.py daemonocle tests
  - py.test -v --cov=daemonocle --cov-report=term-missing tests
after_success:
  - coveralls
